///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddBoard recording.
    /// </summary>
    [TestModule("34435cd5-3e25-4205-9ae0-563bd0e5dae4", ModuleType.Recording, 1)]
    public partial class AddBoard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrelloTestRepository repository.
        /// </summary>
        public static TrelloTestRepository repo = TrelloTestRepository.Instance;

        static AddBoard instance = new AddBoard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddBoard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddBoard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(0));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoardInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoardInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoard' at 114;12.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoardInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.CreateNewBoard.Click("114;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LayerManagerOverlay.Text' at 64;20.", repo.ApplicationUnderTest.LayerManagerOverlay.TextInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.LayerManagerOverlay.Text.Click("64;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'TestRanorexBoard' with focus on 'ApplicationUnderTest.LayerManagerOverlay.Text'.", repo.ApplicationUnderTest.LayerManagerOverlay.TextInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.LayerManagerOverlay.Text.PressKeys("TestRanorexBoard");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LayerManagerOverlay.Blue' at Center.", repo.ApplicationUnderTest.LayerManagerOverlay.BlueInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.LayerManagerOverlay.Blue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LayerManagerOverlay.CreateBoard' at Center.", repo.ApplicationUnderTest.LayerManagerOverlay.CreateBoardInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.LayerManagerOverlay.CreateBoard.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='TestRanorexBoard') on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexBoard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexBoardInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexBoardInfo, "InnerText", "TestRanorexBoard");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
