///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ArchiveCard recording.
    /// </summary>
    [TestModule("bb4ae740-ad43-4017-a9ac-092cbbef89dc", ModuleType.Recording, 1)]
    public partial class ArchiveCard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrelloTestRepository repository.
        /// </summary>
        public static TrelloTestRepository repo = TrelloTestRepository.Instance;

        static ArchiveCard instance = new ArchiveCard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ArchiveCard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ArchiveCard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard' at 148;11.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard.Click("148;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Archive' at 33;12.", repo.ApplicationUnderTest.ArchiveInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Archive.Click("33;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Delete' at 33;2.", repo.ApplicationUnderTest.DeleteInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Delete.Click("33;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 102;12.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Submit.Click("102;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(4));
            Validate.NotExists(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
