///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("1f2b5175-d942-4d22-bc53-8a6e777c006b", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrelloTestRepository repository.
        /// </summary>
        public static TrelloTestRepository repo = TrelloTestRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trello.LogIn' at 60;24.", repo.Trello.LogInInfo, new RecordItemIndex(0));
            repo.Trello.LogIn.Click("60;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trello.User' at 85;33.", repo.Trello.UserInfo, new RecordItemIndex(1));
            repo.Trello.User.Click("85;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hurem9@hotmail.com' with focus on 'Trello.User'.", repo.Trello.UserInfo, new RecordItemIndex(2));
            repo.Trello.User.PressKeys("hurem9@hotmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trello.InnerSection' at 1586;120.", repo.Trello.InnerSectionInfo, new RecordItemIndex(3));
            repo.Trello.InnerSection.Click("1586;120");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Trello.Login1' at Center.", repo.Trello.Login1Info, new RecordItemIndex(4));
            repo.Trello.Login1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogInToContinueLogInWithAtlassi.Password' at 109;9.", repo.LogInToContinueLogInWithAtlassi.PasswordInfo, new RecordItemIndex(5));
            repo.LogInToContinueLogInWithAtlassi.Password.Click("109;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qpus2021@' with focus on 'LogInToContinueLogInWithAtlassi'.", repo.LogInToContinueLogInWithAtlassi.SelfInfo, new RecordItemIndex(6));
            repo.LogInToContinueLogInWithAtlassi.Self.EnsureVisible();
            Keyboard.Press("qpus2021@");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LogInToContinueLogInWithAtlassi.LogIn' at 34;22.", repo.LogInToContinueLogInWithAtlassi.LogInInfo, new RecordItemIndex(7));
            repo.LogInToContinueLogInWithAtlassi.LogIn.Click("34;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Trello.TrelloWorkspace'.", repo.Trello.TrelloWorkspaceInfo, new RecordItemIndex(8));
            Validate.Exists(repo.Trello.TrelloWorkspaceInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
