///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MoveCardToDoneAndArchive recording.
    /// </summary>
    [TestModule("bb4ae740-ad43-4017-a9ac-092cbbef89dc", ModuleType.Recording, 1)]
    public partial class MoveCardToDoneAndArchive : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrelloTestRepository repository.
        /// </summary>
        public static TrelloTestRepository repo = TrelloTestRepository.Instance;

        static MoveCardToDoneAndArchive instance = new MoveCardToDoneAndArchive();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MoveCardToDoneAndArchive()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MoveCardToDoneAndArchive Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard' at 88;8.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard.MoveTo("88;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard' at 929;7.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard.MoveTo("929;7");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard' at 119;15.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard.Click("119;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.WindowOverlay' at 1907;476.", repo.ApplicationUnderTest.WindowOverlayInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.WindowOverlay.MoveTo("1907;476");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.WindowOverlay' at 1917;926.", repo.ApplicationUnderTest.WindowOverlayInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.WindowOverlay.MoveTo("1917;926");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Archive1' at 31;13.", repo.ApplicationUnderTest.Archive1Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Archive1.Click("31;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.WindowOverlay' at 264;358.", repo.ApplicationUnderTest.WindowOverlayInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.WindowOverlay.Click("264;358");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(7));
            Validate.NotExists(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
