///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TrelloBoard_Card recording.
    /// </summary>
    [TestModule("70931e9f-9c74-4256-a365-11085088874e", ModuleType.Recording, 1)]
    public partial class TrelloBoard_Card : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TrelloTestRepository repository.
        /// </summary>
        public static TrelloTestRepository repo = TrelloTestRepository.Instance;

        static TrelloBoard_Card instance = new TrelloBoard_Card();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TrelloBoard_Card()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TrelloBoard_Card Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCard' at 90;5.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCardInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCard.Click("90;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test Ranorex Card' with focus on 'ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCardInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.EnterATitleForThisCard.PressKeys("Test Ranorex Card");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.Submit' at 38;17.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.SubmitInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.Submit.Click("38;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard' at 138;3.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard.Click("138;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Archive' at 12;7.", repo.ApplicationUnderTest.ArchiveInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Archive.Click("12;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Delete' at 5;5.", repo.ApplicationUnderTest.DeleteInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Delete.Click("5;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 125;14.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Submit.Click("125;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCard'.", repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo, new RecordItemIndex(8));
            Validate.NotExists(repo.ApplicationUnderTest.BoardWrapperIsShowMenu.TestRanorexCardInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
