///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TrelloTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TrelloTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ba6f2009-d8d0-4c76-a02c-bdf2a68639ab")]
    public partial class TrelloTestRepository : RepoGenBaseFolder
    {
        static TrelloTestRepository instance = new TrelloTestRepository();
        TrelloTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TrelloTestRepositoryFolders.TrelloAppFolder _trello;
        TrelloTestRepositoryFolders.LogInToContinueLogInWithAtlassiAppFolder _logintocontinueloginwithatlassi;
        TrelloTestRepositoryFolders.AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder _authatlassiancomloginstateeqhkfo2sbwx;
        TrelloTestRepositoryFolders.ExplorerAppFolder _explorer;
        TrelloTestRepositoryFolders.Explorer1AppFolder _explorer1;
        TrelloTestRepositoryFolders.TaskSwitchingAppFolder _taskswitching;

        /// <summary>
        /// Gets the singleton class instance representing the TrelloTestRepository element repository.
        /// </summary>
        [RepositoryFolder("ba6f2009-d8d0-4c76-a02c-bdf2a68639ab")]
        public static TrelloTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TrelloTestRepository() 
            : base("TrelloTestRepository", "/", null, 0, false, "ba6f2009-d8d0-4c76-a02c-bdf2a68639ab", ".\\RepositoryImages\\TrelloTestRepositoryba6f2009.rximgres")
        {
            _applicationundertest = new TrelloTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _trello = new TrelloTestRepositoryFolders.TrelloAppFolder(this);
            _logintocontinueloginwithatlassi = new TrelloTestRepositoryFolders.LogInToContinueLogInWithAtlassiAppFolder(this);
            _authatlassiancomloginstateeqhkfo2sbwx = new TrelloTestRepositoryFolders.AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder(this);
            _explorer = new TrelloTestRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new TrelloTestRepositoryFolders.Explorer1AppFolder(this);
            _taskswitching = new TrelloTestRepositoryFolders.TaskSwitchingAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ba6f2009-d8d0-4c76-a02c-bdf2a68639ab")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("0d69f230-0088-4d27-bde7-648c3b1ce0bc")]
        public virtual TrelloTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Trello folder.
        /// </summary>
        [RepositoryFolder("c8c57785-d070-4d3c-9b55-496fe75e4e67")]
        public virtual TrelloTestRepositoryFolders.TrelloAppFolder Trello
        {
            get { return _trello; }
        }

        /// <summary>
        /// The LogInToContinueLogInWithAtlassi folder.
        /// </summary>
        [RepositoryFolder("35894d13-dc10-42a3-a8c1-2fb4aadb15fe")]
        public virtual TrelloTestRepositoryFolders.LogInToContinueLogInWithAtlassiAppFolder LogInToContinueLogInWithAtlassi
        {
            get { return _logintocontinueloginwithatlassi; }
        }

        /// <summary>
        /// The AuthAtlassianComLoginstateEqhKFo2SBWX folder.
        /// </summary>
        [RepositoryFolder("55777400-dd61-4fe6-abf9-acf646ea3903")]
        public virtual TrelloTestRepositoryFolders.AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder AuthAtlassianComLoginstateEqhKFo2SBWX
        {
            get { return _authatlassiancomloginstateeqhkfo2sbwx; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("3687dc24-fbc3-4f18-9a2b-0e6c629243e7")]
        public virtual TrelloTestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("c418af72-51c0-4c95-bcc8-e3c1d615d731")]
        public virtual TrelloTestRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The TaskSwitching folder.
        /// </summary>
        [RepositoryFolder("d04e7136-b430-4625-a880-270ec4c655a5")]
        public virtual TrelloTestRepositoryFolders.TaskSwitchingAppFolder TaskSwitching
        {
            get { return _taskswitching; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TrelloTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("0d69f230-0088-4d27-bde7-648c3b1ce0bc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            TrelloTestRepositoryFolders.BoardWrapperIsShowMenuFolder _boardwrapperisshowmenu;
            TrelloTestRepositoryFolders.LayerManagerOverlayFolder _layermanageroverlay;
            RepoItemInfo _submitInfo;
            RepoItemInfo _addacardInfo;
            RepoItemInfo _archiveInfo;
            RepoItemInfo _httpstrellocomcrcu44b7j3testranInfo;
            RepoItemInfo _boardInfo;
            RepoItemInfo _addacard1Info;
            RepoItemInfo _windowoverlayInfo;
            RepoItemInfo _archive1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='trello.com']", parentFolder, 30000, null, false, "0d69f230-0088-4d27-bde7-648c3b1ce0bc", "")
            {
                _boardwrapperisshowmenu = new TrelloTestRepositoryFolders.BoardWrapperIsShowMenuFolder(this);
                _layermanageroverlay = new TrelloTestRepositoryFolders.LayerManagerOverlayFolder(this);
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'chrome-container']/div[4]/div/div[2]//input[@type='submit']", "", 30000, null, "032e7a25-d88c-4141-a2f4-fd29e30e5562");
                _addacardInfo = new RepoItemInfo(this, "AddACard", ".//div[#'board']/div[1]//a[@href>'https://trello.com/b/tN1q']/span[@innertext='Add a card']", "", 30000, null, "23f54f8a-d128-4011-89c3-fac71a779094");
                _archiveInfo = new RepoItemInfo(this, "Archive", ".//div[#'chrome-container']/div[7]/div/div[2]/a[8]/span[@innertext='Archive']", "", 30000, null, "abf848d0-3a47-4517-91de-1ae01af06a10");
                _httpstrellocomcrcu44b7j3testranInfo = new RepoItemInfo(this, "HttpsTrelloComCRCU44b7j3TestRan", ".//div[#'chrome-container']/div[3]/div/div/a[@href>'https://trello.com/c/rCU4']", "", 30000, null, "e46b284f-76bc-42fc-8050-efd97c040562");
                _boardInfo = new RepoItemInfo(this, "Board", ".//div[#'board']", "", 30000, null, "7f59948d-ccde-4fc9-b1e6-1585d4df15f4");
                _addacard1Info = new RepoItemInfo(this, "AddACard1", ".//div[#'board']/div[1]/div/div[3]/a[@href>'https://trello.com/b/r8Gy']/span[@innertext='Add a card']", "", 30000, null, "1e03d17a-68ba-494d-b5ba-3425fc34bf64");
                _windowoverlayInfo = new RepoItemInfo(this, "WindowOverlay", ".//div[#'chrome-container']/div[3]", "", 30000, null, "226e158e-57df-4805-8817-cd477a75ae23");
                _archive1Info = new RepoItemInfo(this, "Archive1", ".//div[#'chrome-container']/div[3]/div/div/div/div[5]//a[@title='Archive']/span[@title='Archive']", "", 30000, null, "12cda572-9512-456e-9912-5c4f0200d428");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0d69f230-0088-4d27-bde7-648c3b1ce0bc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0d69f230-0088-4d27-bde7-648c3b1ce0bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("032e7a25-d88c-4141-a2f4-fd29e30e5562")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("032e7a25-d88c-4141-a2f4-fd29e30e5562")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The AddACard item.
            /// </summary>
            [RepositoryItem("23f54f8a-d128-4011-89c3-fac71a779094")]
            public virtual Ranorex.SpanTag AddACard
            {
                get
                {
                    return _addacardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddACard item info.
            /// </summary>
            [RepositoryItemInfo("23f54f8a-d128-4011-89c3-fac71a779094")]
            public virtual RepoItemInfo AddACardInfo
            {
                get
                {
                    return _addacardInfo;
                }
            }

            /// <summary>
            /// The Archive item.
            /// </summary>
            [RepositoryItem("abf848d0-3a47-4517-91de-1ae01af06a10")]
            public virtual Ranorex.SpanTag Archive
            {
                get
                {
                    return _archiveInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Archive item info.
            /// </summary>
            [RepositoryItemInfo("abf848d0-3a47-4517-91de-1ae01af06a10")]
            public virtual RepoItemInfo ArchiveInfo
            {
                get
                {
                    return _archiveInfo;
                }
            }

            /// <summary>
            /// The HttpsTrelloComCRCU44b7j3TestRan item.
            /// </summary>
            [RepositoryItem("e46b284f-76bc-42fc-8050-efd97c040562")]
            public virtual Ranorex.ATag HttpsTrelloComCRCU44b7j3TestRan
            {
                get
                {
                    return _httpstrellocomcrcu44b7j3testranInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsTrelloComCRCU44b7j3TestRan item info.
            /// </summary>
            [RepositoryItemInfo("e46b284f-76bc-42fc-8050-efd97c040562")]
            public virtual RepoItemInfo HttpsTrelloComCRCU44b7j3TestRanInfo
            {
                get
                {
                    return _httpstrellocomcrcu44b7j3testranInfo;
                }
            }

            /// <summary>
            /// The Board item.
            /// </summary>
            [RepositoryItem("7f59948d-ccde-4fc9-b1e6-1585d4df15f4")]
            public virtual Ranorex.DivTag Board
            {
                get
                {
                    return _boardInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Board item info.
            /// </summary>
            [RepositoryItemInfo("7f59948d-ccde-4fc9-b1e6-1585d4df15f4")]
            public virtual RepoItemInfo BoardInfo
            {
                get
                {
                    return _boardInfo;
                }
            }

            /// <summary>
            /// The AddACard1 item.
            /// </summary>
            [RepositoryItem("1e03d17a-68ba-494d-b5ba-3425fc34bf64")]
            public virtual Ranorex.SpanTag AddACard1
            {
                get
                {
                    return _addacard1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AddACard1 item info.
            /// </summary>
            [RepositoryItemInfo("1e03d17a-68ba-494d-b5ba-3425fc34bf64")]
            public virtual RepoItemInfo AddACard1Info
            {
                get
                {
                    return _addacard1Info;
                }
            }

            /// <summary>
            /// The WindowOverlay item.
            /// </summary>
            [RepositoryItem("226e158e-57df-4805-8817-cd477a75ae23")]
            public virtual Ranorex.DivTag WindowOverlay
            {
                get
                {
                    return _windowoverlayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The WindowOverlay item info.
            /// </summary>
            [RepositoryItemInfo("226e158e-57df-4805-8817-cd477a75ae23")]
            public virtual RepoItemInfo WindowOverlayInfo
            {
                get
                {
                    return _windowoverlayInfo;
                }
            }

            /// <summary>
            /// The Archive1 item.
            /// </summary>
            [RepositoryItem("12cda572-9512-456e-9912-5c4f0200d428")]
            public virtual Ranorex.SpanTag Archive1
            {
                get
                {
                    return _archive1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Archive1 item info.
            /// </summary>
            [RepositoryItemInfo("12cda572-9512-456e-9912-5c4f0200d428")]
            public virtual RepoItemInfo Archive1Info
            {
                get
                {
                    return _archive1Info;
                }
            }

            /// <summary>
            /// The BoardWrapperIsShowMenu folder.
            /// </summary>
            [RepositoryFolder("5f2bddd6-025e-4cba-b74a-db392469ed2f")]
            public virtual TrelloTestRepositoryFolders.BoardWrapperIsShowMenuFolder BoardWrapperIsShowMenu
            {
                get { return _boardwrapperisshowmenu; }
            }

            /// <summary>
            /// The LayerManagerOverlay folder.
            /// </summary>
            [RepositoryFolder("9f0e7fdb-6755-487d-9b8f-217f2a7700f6")]
            public virtual TrelloTestRepositoryFolders.LayerManagerOverlayFolder LayerManagerOverlay
            {
                get { return _layermanageroverlay; }
            }
        }

        /// <summary>
        /// The BoardWrapperIsShowMenuFolder folder.
        /// </summary>
        [RepositoryFolder("5f2bddd6-025e-4cba-b74a-db392469ed2f")]
        public partial class BoardWrapperIsShowMenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testranorexboardInfo;
            RepoItemInfo _showmenuInfo;
            RepoItemInfo _createnewboardInfo;
            RepoItemInfo _boardmenucontentjsboardmenucontentInfo;
            RepoItemInfo _atagmoreInfo;
            RepoItemInfo _atagcloseboardInfo;
            RepoItemInfo _permanentlydeleteboardInfo;
            RepoItemInfo _boardnotfoundInfo;
            RepoItemInfo _enteratitleforthiscardInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _iconediticonsmjscardmenulistcardInfo;
            RepoItemInfo _testranorexcardInfo;
            RepoItemInfo _testranorexcard1Info;
            RepoItemInfo _testranorexcard2Info;

            /// <summary>
            /// Creates a new BoardWrapperIsShowMenu  folder.
            /// </summary>
            public BoardWrapperIsShowMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("BoardWrapperIsShowMenu", ".//div[#'content']/div", parentFolder, 30000, null, false, "5f2bddd6-025e-4cba-b74a-db392469ed2f", "")
            {
                _testranorexboardInfo = new RepoItemInfo(this, "TestRanorexBoard", "div[1]/div[1]/div[2]/h1[@innertext='TestRanorexBoard']", "", 30000, null, "4186e6bc-88f5-475a-9113-943208d08ca6");
                _showmenuInfo = new RepoItemInfo(this, "ShowMenu", "div[1]/div[1]/div[5]/a[4]/span[@innertext='Show menu']", "", 30000, null, "352877dd-9587-4e46-bea0-30fa0ac28ac0");
                _createnewboardInfo = new RepoItemInfo(this, "CreateNewBoard", "div[2]/div/div/div/div/div[2]/div/div/div[2]/div[3]/ul//span[@innertext='Create new board']", "", 30000, null, "2b5f80ed-856e-4bb0-b138-a2db67d0dd55");
                _boardmenucontentjsboardmenucontentInfo = new RepoItemInfo(this, "BoardMenuContentJsBoardMenuContent", "div[2]/div/div/div[2]", "", 30000, null, "fa4f0242-7ec9-4dc1-a4c3-60c176577c06");
                _atagmoreInfo = new RepoItemInfo(this, "ATagMore", "div[2]/div/div/div[2]/div/ul[1]/li[5]/a[@innertext=' More']", "", 30000, null, "f6737c3c-d584-4905-aecd-c1a69c3c0da4");
                _atagcloseboardInfo = new RepoItemInfo(this, "ATagCloseBoard", "div[2]/div/div/div[2]/div/ul[3]/?/?/a[@innertext=' Close board…']", "", 30000, null, "81f3d12f-4f4e-40f9-bfd7-4802a2bdd3a1");
                _permanentlydeleteboardInfo = new RepoItemInfo(this, "PermanentlyDeleteBoard", "div/div/p[2]/a[@innertext='Permanently delete board…']", "", 30000, null, "489b4652-c8d5-4e11-a8f3-bb2d3cbb1adf");
                _boardnotfoundInfo = new RepoItemInfo(this, "BoardNotFound", ".//h1[@innertext='Board not found.']", "", 30000, null, "6f8d9b22-6897-43aa-895d-3bbaf4f72776");
                _enteratitleforthiscardInfo = new RepoItemInfo(this, "EnterATitleForThisCard", ".//textarea[@placeholder='Enter a title for this card…']", "", 30000, null, "216bb8b2-5913-4b36-803c-4b22c4da2e45");
                _submitInfo = new RepoItemInfo(this, "Submit", "div/div[3]/div[@id='board']/div[1]/div/div[2]//input[@value='Add card']", "", 30000, null, "3083cca0-16d7-4a64-a477-56490cf91dd6");
                _iconediticonsmjscardmenulistcardInfo = new RepoItemInfo(this, "IconEditIconSmJsCardMenuListCard", "div[3]//a/span", "", 30000, null, "e793bbaa-3688-4dff-9eea-a6a25101585c");
                _testranorexcardInfo = new RepoItemInfo(this, "TestRanorexCard", ".//a[@href>'https://trello.com/c/aRie']/div[3]/span[@innertext='Test Ranorex Card']", "", 30000, null, "336b4595-16f6-4a40-bdfc-6bd80a567f29");
                _testranorexcard1Info = new RepoItemInfo(this, "TestRanorexCard1", "div[3]//a/div[3]/span[@innertext='Test Ranorex Card']", "", 30000, null, "a85dadd0-704e-40f8-8d97-af7e76deca8c");
                _testranorexcard2Info = new RepoItemInfo(this, "TestRanorexCard2", "div[3]//a/div[3]/span[@innertext='Test Ranorex Card']", "", 30000, null, "6879ea3b-a3a1-497a-a995-2dcb15737012");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f2bddd6-025e-4cba-b74a-db392469ed2f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f2bddd6-025e-4cba-b74a-db392469ed2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestRanorexBoard item.
            /// </summary>
            [RepositoryItem("4186e6bc-88f5-475a-9113-943208d08ca6")]
            public virtual Ranorex.H1Tag TestRanorexBoard
            {
                get
                {
                    return _testranorexboardInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The TestRanorexBoard item info.
            /// </summary>
            [RepositoryItemInfo("4186e6bc-88f5-475a-9113-943208d08ca6")]
            public virtual RepoItemInfo TestRanorexBoardInfo
            {
                get
                {
                    return _testranorexboardInfo;
                }
            }

            /// <summary>
            /// The ShowMenu item.
            /// </summary>
            [RepositoryItem("352877dd-9587-4e46-bea0-30fa0ac28ac0")]
            public virtual Ranorex.SpanTag ShowMenu
            {
                get
                {
                    return _showmenuInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ShowMenu item info.
            /// </summary>
            [RepositoryItemInfo("352877dd-9587-4e46-bea0-30fa0ac28ac0")]
            public virtual RepoItemInfo ShowMenuInfo
            {
                get
                {
                    return _showmenuInfo;
                }
            }

            /// <summary>
            /// The CreateNewBoard item.
            /// </summary>
            [RepositoryItem("2b5f80ed-856e-4bb0-b138-a2db67d0dd55")]
            public virtual Ranorex.SpanTag CreateNewBoard
            {
                get
                {
                    return _createnewboardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreateNewBoard item info.
            /// </summary>
            [RepositoryItemInfo("2b5f80ed-856e-4bb0-b138-a2db67d0dd55")]
            public virtual RepoItemInfo CreateNewBoardInfo
            {
                get
                {
                    return _createnewboardInfo;
                }
            }

            /// <summary>
            /// The BoardMenuContentJsBoardMenuContent item.
            /// </summary>
            [RepositoryItem("fa4f0242-7ec9-4dc1-a4c3-60c176577c06")]
            public virtual Ranorex.DivTag BoardMenuContentJsBoardMenuContent
            {
                get
                {
                    return _boardmenucontentjsboardmenucontentInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BoardMenuContentJsBoardMenuContent item info.
            /// </summary>
            [RepositoryItemInfo("fa4f0242-7ec9-4dc1-a4c3-60c176577c06")]
            public virtual RepoItemInfo BoardMenuContentJsBoardMenuContentInfo
            {
                get
                {
                    return _boardmenucontentjsboardmenucontentInfo;
                }
            }

            /// <summary>
            /// The ATagMore item.
            /// </summary>
            [RepositoryItem("f6737c3c-d584-4905-aecd-c1a69c3c0da4")]
            public virtual Ranorex.ATag ATagMore
            {
                get
                {
                    return _atagmoreInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagMore item info.
            /// </summary>
            [RepositoryItemInfo("f6737c3c-d584-4905-aecd-c1a69c3c0da4")]
            public virtual RepoItemInfo ATagMoreInfo
            {
                get
                {
                    return _atagmoreInfo;
                }
            }

            /// <summary>
            /// The ATagCloseBoard item.
            /// </summary>
            [RepositoryItem("81f3d12f-4f4e-40f9-bfd7-4802a2bdd3a1")]
            public virtual Ranorex.ATag ATagCloseBoard
            {
                get
                {
                    return _atagcloseboardInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagCloseBoard item info.
            /// </summary>
            [RepositoryItemInfo("81f3d12f-4f4e-40f9-bfd7-4802a2bdd3a1")]
            public virtual RepoItemInfo ATagCloseBoardInfo
            {
                get
                {
                    return _atagcloseboardInfo;
                }
            }

            /// <summary>
            /// The PermanentlyDeleteBoard item.
            /// </summary>
            [RepositoryItem("489b4652-c8d5-4e11-a8f3-bb2d3cbb1adf")]
            public virtual Ranorex.ATag PermanentlyDeleteBoard
            {
                get
                {
                    return _permanentlydeleteboardInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The PermanentlyDeleteBoard item info.
            /// </summary>
            [RepositoryItemInfo("489b4652-c8d5-4e11-a8f3-bb2d3cbb1adf")]
            public virtual RepoItemInfo PermanentlyDeleteBoardInfo
            {
                get
                {
                    return _permanentlydeleteboardInfo;
                }
            }

            /// <summary>
            /// The BoardNotFound item.
            /// </summary>
            [RepositoryItem("6f8d9b22-6897-43aa-895d-3bbaf4f72776")]
            public virtual Ranorex.H1Tag BoardNotFound
            {
                get
                {
                    return _boardnotfoundInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The BoardNotFound item info.
            /// </summary>
            [RepositoryItemInfo("6f8d9b22-6897-43aa-895d-3bbaf4f72776")]
            public virtual RepoItemInfo BoardNotFoundInfo
            {
                get
                {
                    return _boardnotfoundInfo;
                }
            }

            /// <summary>
            /// The EnterATitleForThisCard item.
            /// </summary>
            [RepositoryItem("216bb8b2-5913-4b36-803c-4b22c4da2e45")]
            public virtual Ranorex.TextAreaTag EnterATitleForThisCard
            {
                get
                {
                    return _enteratitleforthiscardInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The EnterATitleForThisCard item info.
            /// </summary>
            [RepositoryItemInfo("216bb8b2-5913-4b36-803c-4b22c4da2e45")]
            public virtual RepoItemInfo EnterATitleForThisCardInfo
            {
                get
                {
                    return _enteratitleforthiscardInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("3083cca0-16d7-4a64-a477-56490cf91dd6")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("3083cca0-16d7-4a64-a477-56490cf91dd6")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The IconEditIconSmJsCardMenuListCard item.
            /// </summary>
            [RepositoryItem("e793bbaa-3688-4dff-9eea-a6a25101585c")]
            public virtual Ranorex.SpanTag IconEditIconSmJsCardMenuListCard
            {
                get
                {
                    return _iconediticonsmjscardmenulistcardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The IconEditIconSmJsCardMenuListCard item info.
            /// </summary>
            [RepositoryItemInfo("e793bbaa-3688-4dff-9eea-a6a25101585c")]
            public virtual RepoItemInfo IconEditIconSmJsCardMenuListCardInfo
            {
                get
                {
                    return _iconediticonsmjscardmenulistcardInfo;
                }
            }

            /// <summary>
            /// The TestRanorexCard item.
            /// </summary>
            [RepositoryItem("336b4595-16f6-4a40-bdfc-6bd80a567f29")]
            public virtual Ranorex.SpanTag TestRanorexCard
            {
                get
                {
                    return _testranorexcardInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TestRanorexCard item info.
            /// </summary>
            [RepositoryItemInfo("336b4595-16f6-4a40-bdfc-6bd80a567f29")]
            public virtual RepoItemInfo TestRanorexCardInfo
            {
                get
                {
                    return _testranorexcardInfo;
                }
            }

            /// <summary>
            /// The TestRanorexCard1 item.
            /// </summary>
            [RepositoryItem("a85dadd0-704e-40f8-8d97-af7e76deca8c")]
            public virtual Ranorex.SpanTag TestRanorexCard1
            {
                get
                {
                    return _testranorexcard1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TestRanorexCard1 item info.
            /// </summary>
            [RepositoryItemInfo("a85dadd0-704e-40f8-8d97-af7e76deca8c")]
            public virtual RepoItemInfo TestRanorexCard1Info
            {
                get
                {
                    return _testranorexcard1Info;
                }
            }

            /// <summary>
            /// The TestRanorexCard2 item.
            /// </summary>
            [RepositoryItem("6879ea3b-a3a1-497a-a995-2dcb15737012")]
            public virtual Ranorex.SpanTag TestRanorexCard2
            {
                get
                {
                    return _testranorexcard2Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TestRanorexCard2 item info.
            /// </summary>
            [RepositoryItemInfo("6879ea3b-a3a1-497a-a995-2dcb15737012")]
            public virtual RepoItemInfo TestRanorexCard2Info
            {
                get
                {
                    return _testranorexcard2Info;
                }
            }
        }

        /// <summary>
        /// The LayerManagerOverlayFolder folder.
        /// </summary>
        [RepositoryFolder("9f0e7fdb-6755-487d-9b8f-217f2a7700f6")]
        public partial class LayerManagerOverlayFolder : RepoGenBaseFolder
        {
            RepoItemInfo _brownandgreenmountainunderwhiteskyInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _createboardInfo;
            RepoItemInfo _blueInfo;

            /// <summary>
            /// Creates a new LayerManagerOverlay  folder.
            /// </summary>
            public LayerManagerOverlayFolder(RepoGenBaseFolder parentFolder) :
                    base("LayerManagerOverlay", ".//div[#'layer-manager-overlay']", parentFolder, 30000, null, false, "9f0e7fdb-6755-487d-9b8f-217f2a7700f6", "")
            {
                _brownandgreenmountainunderwhiteskyInfo = new RepoItemInfo(this, "BrownAndGreenMountainUnderWhiteSky", ".//ul/li[4]/button[@title>'brown and green mountain under']", "", 30000, null, "8e44165e-3a26-47d6-b4df-dcfe2a0de8f3");
                _textInfo = new RepoItemInfo(this, "Text", "div/div/div[1]/?/?/input[@type='text']", "", 30000, null, "e8c4cd7a-b8b1-4e3d-8cd4-7e739f5492df");
                _createboardInfo = new RepoItemInfo(this, "CreateBoard", "div/div/div[2]/?/?/button[@innertext='Create board']", "", 30000, null, "89b927ca-83f4-4e5b-b56a-757fe6ef0cc0");
                _blueInfo = new RepoItemInfo(this, "Blue", ".//ul/li[5]/button[@title='blue']", "", 30000, null, "9d6abcda-2496-44d5-8340-c44399cccc10");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f0e7fdb-6755-487d-9b8f-217f2a7700f6")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f0e7fdb-6755-487d-9b8f-217f2a7700f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BrownAndGreenMountainUnderWhiteSky item.
            /// </summary>
            [RepositoryItem("8e44165e-3a26-47d6-b4df-dcfe2a0de8f3")]
            public virtual Ranorex.ButtonTag BrownAndGreenMountainUnderWhiteSky
            {
                get
                {
                    return _brownandgreenmountainunderwhiteskyInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BrownAndGreenMountainUnderWhiteSky item info.
            /// </summary>
            [RepositoryItemInfo("8e44165e-3a26-47d6-b4df-dcfe2a0de8f3")]
            public virtual RepoItemInfo BrownAndGreenMountainUnderWhiteSkyInfo
            {
                get
                {
                    return _brownandgreenmountainunderwhiteskyInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("e8c4cd7a-b8b1-4e3d-8cd4-7e739f5492df")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("e8c4cd7a-b8b1-4e3d-8cd4-7e739f5492df")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The CreateBoard item.
            /// </summary>
            [RepositoryItem("89b927ca-83f4-4e5b-b56a-757fe6ef0cc0")]
            public virtual Ranorex.ButtonTag CreateBoard
            {
                get
                {
                    return _createboardInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CreateBoard item info.
            /// </summary>
            [RepositoryItemInfo("89b927ca-83f4-4e5b-b56a-757fe6ef0cc0")]
            public virtual RepoItemInfo CreateBoardInfo
            {
                get
                {
                    return _createboardInfo;
                }
            }

            /// <summary>
            /// The Blue item.
            /// </summary>
            [RepositoryItem("9d6abcda-2496-44d5-8340-c44399cccc10")]
            public virtual Ranorex.ButtonTag Blue
            {
                get
                {
                    return _blueInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Blue item info.
            /// </summary>
            [RepositoryItemInfo("9d6abcda-2496-44d5-8340-c44399cccc10")]
            public virtual RepoItemInfo BlueInfo
            {
                get
                {
                    return _blueInfo;
                }
            }
        }

        /// <summary>
        /// The TrelloAppFolder folder.
        /// </summary>
        [RepositoryFolder("c8c57785-d070-4d3c-9b55-496fe75e4e67")]
        public partial class TrelloAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _login1Info;
            RepoItemInfo _trelloworkspaceInfo;
            RepoItemInfo _spantag24awinhreyjnbfayxvcytxemtcsjInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _ptagyoureallloggedoutsonowwhatInfo;
            RepoItemInfo _innersectionInfo;
            RepoItemInfo _userInfo;

            /// <summary>
            /// Creates a new Trello  folder.
            /// </summary>
            public TrelloAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Trello", "/dom[@domain='trello.com']", parentFolder, 30000, null, false, "c8c57785-d070-4d3c-9b55-496fe75e4e67", "")
            {
                _loginInfo = new RepoItemInfo(this, "LogIn", "?/?/header/nav/?/?/a[@innertext='Log in']", "", 30000, null, "bc11b328-c8f4-4612-a53a-bcee790d799a");
                _login1Info = new RepoItemInfo(this, "Login1", ".//input[#'login']", "", 30000, null, "3e0b7d51-5904-4744-aadf-4f10c91ae5a8");
                _trelloworkspaceInfo = new RepoItemInfo(this, "TrelloWorkspace", ".//div[#'content']/div/div[2]/div/div/div/div/div[1]/nav/div[2]/?/?/ul/?/?/a[@href>'https://trello.com/userwo']/span[@innertext='Trello workspace']", "", 30000, null, "369cca49-e211-4d9c-b857-8df09e002d65");
                _spantag24awinhreyjnbfayxvcytxemtcsjInfo = new RepoItemInfo(this, "SpanTag24AWINHReYjNBfAYXvcYtXemTcSj", ".//div[#'header']/?/?/button[@title='Jasmin H. (jasminh14)']/?/?/span", "", 30000, null, "5d0f2b37-3fbe-4dd3-a017-4a614208f911");
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//section/?/?/nav/ul/li[8]/?/?/span[@innertext='Log out']", "", 30000, null, "695da4f2-6556-440a-b88a-df506b4c7c58");
                _ptagyoureallloggedoutsonowwhatInfo = new RepoItemInfo(this, "PTagYoureAllLoggedOutSoNowWhat", "body/div[2]/?/?/p[@innertext>' You’re all logged out. So']", "", 30000, null, "9747ad67-9618-41ea-978d-38f196e2492d");
                _innersectionInfo = new RepoItemInfo(this, "InnerSection", "body/div[1]/section", "", 30000, null, "29fb32de-0d98-41fd-8b70-73fef723c413");
                _userInfo = new RepoItemInfo(this, "User", ".//input[#'user']", "", 30000, null, "d09f662f-7b1f-47e9-8ee1-5dda3eed7598");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8c57785-d070-4d3c-9b55-496fe75e4e67")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8c57785-d070-4d3c-9b55-496fe75e4e67")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("bc11b328-c8f4-4612-a53a-bcee790d799a")]
            public virtual Ranorex.ATag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("bc11b328-c8f4-4612-a53a-bcee790d799a")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Login1 item.
            /// </summary>
            [RepositoryItem("3e0b7d51-5904-4744-aadf-4f10c91ae5a8")]
            public virtual Ranorex.InputTag Login1
            {
                get
                {
                    return _login1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login1 item info.
            /// </summary>
            [RepositoryItemInfo("3e0b7d51-5904-4744-aadf-4f10c91ae5a8")]
            public virtual RepoItemInfo Login1Info
            {
                get
                {
                    return _login1Info;
                }
            }

            /// <summary>
            /// The TrelloWorkspace item.
            /// </summary>
            [RepositoryItem("369cca49-e211-4d9c-b857-8df09e002d65")]
            public virtual Ranorex.SpanTag TrelloWorkspace
            {
                get
                {
                    return _trelloworkspaceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TrelloWorkspace item info.
            /// </summary>
            [RepositoryItemInfo("369cca49-e211-4d9c-b857-8df09e002d65")]
            public virtual RepoItemInfo TrelloWorkspaceInfo
            {
                get
                {
                    return _trelloworkspaceInfo;
                }
            }

            /// <summary>
            /// The SpanTag24AWINHReYjNBfAYXvcYtXemTcSj item.
            /// </summary>
            [RepositoryItem("5d0f2b37-3fbe-4dd3-a017-4a614208f911")]
            public virtual Ranorex.SpanTag SpanTag24AWINHReYjNBfAYXvcYtXemTcSj
            {
                get
                {
                    return _spantag24awinhreyjnbfayxvcytxemtcsjInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag24AWINHReYjNBfAYXvcYtXemTcSj item info.
            /// </summary>
            [RepositoryItemInfo("5d0f2b37-3fbe-4dd3-a017-4a614208f911")]
            public virtual RepoItemInfo SpanTag24AWINHReYjNBfAYXvcYtXemTcSjInfo
            {
                get
                {
                    return _spantag24awinhreyjnbfayxvcytxemtcsjInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("695da4f2-6556-440a-b88a-df506b4c7c58")]
            public virtual Ranorex.SpanTag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("695da4f2-6556-440a-b88a-df506b4c7c58")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The PTagYoureAllLoggedOutSoNowWhat item.
            /// </summary>
            [RepositoryItem("9747ad67-9618-41ea-978d-38f196e2492d")]
            public virtual Ranorex.PTag PTagYoureAllLoggedOutSoNowWhat
            {
                get
                {
                    return _ptagyoureallloggedoutsonowwhatInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The PTagYoureAllLoggedOutSoNowWhat item info.
            /// </summary>
            [RepositoryItemInfo("9747ad67-9618-41ea-978d-38f196e2492d")]
            public virtual RepoItemInfo PTagYoureAllLoggedOutSoNowWhatInfo
            {
                get
                {
                    return _ptagyoureallloggedoutsonowwhatInfo;
                }
            }

            /// <summary>
            /// The InnerSection item.
            /// </summary>
            [RepositoryItem("29fb32de-0d98-41fd-8b70-73fef723c413")]
            public virtual Ranorex.SectionTag InnerSection
            {
                get
                {
                    return _innersectionInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The InnerSection item info.
            /// </summary>
            [RepositoryItemInfo("29fb32de-0d98-41fd-8b70-73fef723c413")]
            public virtual RepoItemInfo InnerSectionInfo
            {
                get
                {
                    return _innersectionInfo;
                }
            }

            /// <summary>
            /// The User item.
            /// </summary>
            [RepositoryItem("d09f662f-7b1f-47e9-8ee1-5dda3eed7598")]
            public virtual Ranorex.InputTag User
            {
                get
                {
                    return _userInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The User item info.
            /// </summary>
            [RepositoryItemInfo("d09f662f-7b1f-47e9-8ee1-5dda3eed7598")]
            public virtual RepoItemInfo UserInfo
            {
                get
                {
                    return _userInfo;
                }
            }
        }

        /// <summary>
        /// The LogInToContinueLogInWithAtlassiAppFolder folder.
        /// </summary>
        [RepositoryFolder("35894d13-dc10-42a3-a8c1-2fb4aadb15fe")]
        public partial class LogInToContinueLogInWithAtlassiAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new LogInToContinueLogInWithAtlassi  folder.
            /// </summary>
            public LogInToContinueLogInWithAtlassiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LogInToContinueLogInWithAtlassi", "/dom[@domain='id.atlassian.com']", parentFolder, 30000, null, false, "35894d13-dc10-42a3-a8c1-2fb4aadb15fe", "")
            {
                _logoutInfo = new RepoItemInfo(this, "LogOut", ".//button[#'logout-submit']//span[@innertext='Log out']", "", 30000, null, "765ad9b9-ab55-45e1-8359-1ff00ede446e");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", "", 30000, null, "d9e963d2-979d-4060-b6f4-5d18d92b2bac");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//button[#'login-submit']//span[@innertext='Log in']", "", 30000, null, "9db49805-d5fb-44e0-b0fb-63970e39b24d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("35894d13-dc10-42a3-a8c1-2fb4aadb15fe")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("35894d13-dc10-42a3-a8c1-2fb4aadb15fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("765ad9b9-ab55-45e1-8359-1ff00ede446e")]
            public virtual Ranorex.SpanTag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("765ad9b9-ab55-45e1-8359-1ff00ede446e")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d9e963d2-979d-4060-b6f4-5d18d92b2bac")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d9e963d2-979d-4060-b6f4-5d18d92b2bac")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("9db49805-d5fb-44e0-b0fb-63970e39b24d")]
            public virtual Ranorex.SpanTag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("9db49805-d5fb-44e0-b0fb-63970e39b24d")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder folder.
        /// </summary>
        [RepositoryFolder("55777400-dd61-4fe6-abf9-acf646ea3903")]
        public partial class AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new AuthAtlassianComLoginstateEqhKFo2SBWX  folder.
            /// </summary>
            public AuthAtlassianComLoginstateEqhKFo2SBWXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AuthAtlassianComLoginstateEqhKFo2SBWX", "/dom[@domain='auth.atlassian.com']", parentFolder, 30000, null, false, "55777400-dd61-4fe6-abf9-acf646ea3903", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55777400-dd61-4fe6-abf9-acf646ea3903")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55777400-dd61-4fe6-abf9-acf646ea3903")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("3687dc24-fbc3-4f18-9a2b-0e6c629243e7")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firefox1runningwindowInfo;
            RepoItemInfo _element307Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "3687dc24-fbc3-4f18-9a2b-0e6c629243e7", "")
            {
                _firefox1runningwindowInfo = new RepoItemInfo(this, "Firefox1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[13]", "", 30000, null, "c7e0c099-ea17-475f-ae18-203b33127d29");
                _element307Info = new RepoItemInfo(this, "Element307", "?/?/element[@controlid='307']", "", 30000, null, "10d2e1e9-f0de-4ccd-b1a0-10a55cc40ef6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3687dc24-fbc3-4f18-9a2b-0e6c629243e7")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3687dc24-fbc3-4f18-9a2b-0e6c629243e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Firefox1RunningWindow item.
            /// </summary>
            [RepositoryItem("c7e0c099-ea17-475f-ae18-203b33127d29")]
            public virtual Ranorex.Button Firefox1RunningWindow
            {
                get
                {
                    return _firefox1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Firefox1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("c7e0c099-ea17-475f-ae18-203b33127d29")]
            public virtual RepoItemInfo Firefox1RunningWindowInfo
            {
                get
                {
                    return _firefox1runningwindowInfo;
                }
            }

            /// <summary>
            /// The Element307 item.
            /// </summary>
            [RepositoryItem("10d2e1e9-f0de-4ccd-b1a0-10a55cc40ef6")]
            public virtual Ranorex.Unknown Element307
            {
                get
                {
                    return _element307Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element307 item info.
            /// </summary>
            [RepositoryItemInfo("10d2e1e9-f0de-4ccd-b1a0-10a55cc40ef6")]
            public virtual RepoItemInfo Element307Info
            {
                get
                {
                    return _element307Info;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c418af72-51c0-4c95-bcc8-e3c1d615d731")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@title='']", parentFolder, 30000, null, true, "c418af72-51c0-4c95-bcc8-e3c1d615d731", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c418af72-51c0-4c95-bcc8-e3c1d615d731")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c418af72-51c0-4c95-bcc8-e3c1d615d731")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TaskSwitchingAppFolder folder.
        /// </summary>
        [RepositoryFolder("d04e7136-b430-4625-a880-270ec4c655a5")]
        public partial class TaskSwitchingAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TaskSwitching  folder.
            /// </summary>
            public TaskSwitchingAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TaskSwitching", "/form[@title='Task Switching']", parentFolder, 30000, null, true, "d04e7136-b430-4625-a880-270ec4c655a5", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d04e7136-b430-4625-a880-270ec4c655a5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d04e7136-b430-4625-a880-270ec4c655a5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
